---
# tasks file for ec2
#
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
   name: "{{ item.name }}"
   key_name: "my_key"
   image_id: "{{ item.image }}"

   instance_type: t2.micro
   security_group: default
   region: us-east-1
   profile: "default"

   # If aws CLI not configured, we need to provide aws access key and security key.
   #aws_access_key: "{{ec2_access_key}}" # From vault as defined
   #aws_secret_key: "{{ec2_secret_key}}" # From vault as defined

   network:
     assign_public_ip: true
    

   tags:
      environment: "{{ item.name }}"
  loop:
    - { image: 'ami-08982f1c5bf93d976', name: 'manage-node-1'}
    - { image: 'ami-0360c520857e3138f', name: 'manage-node-2'}
    - { image: 'ami-0360c520857e3138f', name: 'manage-node-3'}
  
